### ISSUE TITLE
Add some model tests related to post, user and target

### ISSUE THREAD

**Issue by TingAnLiu** [dwliao/meetdude#1]
We need some model tests which cover:
1. target_id shouldn't be null when create post
2. user.target_posts should get all posts which target_id is equal to user.id
3. user.posts should get all posts which user_id is equal to user.id
4. post.user should get user which id is equal to post.user_id
5. post.target should get user which id is equal to post.target_id

**Comment by dwliao** [comment]
1. post_spec
2~5.  user_spec

**Comment by dwliao** [comment]
1. post_spec
2~5 user_spac
